--
-- File generated with SQLiteStudio v3.0.2 on Sat Feb 14 21:59:46 2015
--
-- Text encoding used: windows-1252
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Authors
CREATE TABLE IF NOT EXISTS Authors (ID INTEGER PRIMARY KEY, UserName TEXT (32) UNIQUE NOT NULL, Email TEXT (128) UNIQUE)

-- Table: Tilesets
CREATE TABLE IF NOT EXISTS Tilesets (ID INTEGER PRIMARY KEY, Name TEXT (64) NOT NULL, AuthorID INTEGER NOT NULL)

-- Table: Campaigns
CREATE TABLE IF NOT EXISTS Campaigns (ID INTEGER PRIMARY KEY, Name TEXT (64) NOT NULL, AuthorID INTEGER NOT NULL, TilesetID INTEGER NOT NULL)

-- Table: Waves
CREATE TABLE IF NOT EXISTS Waves (CampaignID INTEGER NOT NULL, Number INT (64) NOT NULL, CreepNumber INTEGER (32) NOT NULL, CreepCount INTEGER (64) NOT NULL, SpawnDelay INTEGER (60) NOT NULL, StartingMoney INTEGER (1024))

-- Table: Assets
CREATE TABLE IF NOT EXISTS Assets (ID INTEGER PRIMARY KEY, TilesetID INTEGER NOT NULL, Name TEXT (24) NOT NULL, Number INTEGER (64) NOT NULL, URI TEXT (512) NOT NULL, Type STRING (8) NOT NULL, SubType STRING (16))

COMMIT TRANSACTION;
